import { auditStatement, database, eventAccessClause, requireEventAccess, requireRfqAccess, requireRole, requireWorkspace, revenueEnv } from '@/lib/db';
import { validateUpload } from '@/lib/file-validation';

const clean = (value: unknown, max: number) => typeof value === 'string' ? value.trim().slice(0, max) : '';
const allowedFiles = new Set(['application/pdf','text/plain','text/csv','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','image/png','image/jpeg']);

export async function GET(request: Request) {
  const context=await requireWorkspace(request); const access=eventAccessClause(context,'r.event_id'); const rows=await database().prepare(`SELECT r.id,r.event_id AS eventId,r.title,r.reference,r.requester_company AS requesterCompany,r.contact_name AS contactName,r.delivery_location AS deliveryLocation,r.submission_deadline AS submissionDeadline,r.status,r.processing_status AS processingStatus,r.owner_id AS ownerId,r.created_at AS createdAt,COUNT(DISTINCT i.id) AS itemCount,COUNT(DISTINCT d.id) AS documentCount,(SELECT x.id FROM rfq_ai_extractions x WHERE x.rfq_id=r.id ORDER BY x.created_at DESC LIMIT 1) AS extractionId,(SELECT x.status FROM rfq_ai_extractions x WHERE x.rfq_id=r.id ORDER BY x.created_at DESC LIMIT 1) AS extractionStatus,(SELECT x.result_json FROM rfq_ai_extractions x WHERE x.rfq_id=r.id ORDER BY x.created_at DESC LIMIT 1) AS extractionJson FROM rfqs r LEFT JOIN rfq_items i ON i.rfq_id=r.id LEFT JOIN rfq_documents d ON d.rfq_id=r.id WHERE r.workspace_id=?${access.sql} GROUP BY r.id ORDER BY r.submission_deadline IS NULL,r.submission_deadline,r.created_at DESC`).bind(context.workspace.id,...access.bindings).all(); return Response.json({rfqs:rows.results});
}

export async function POST(request: Request) {
  const context=await requireWorkspace(request); requireRole(context,['owner','admin','manager','salesperson']); const contentType=request.headers.get('content-type')||''; const form=contentType.includes('multipart/form-data')?await request.formData():null; const body=form?Object.fromEntries(form.entries()):await request.json().catch(()=>null) as Record<string,unknown>|null; if(!body)return Response.json({error:'Invalid request body.'},{status:400}); const action=clean(body.action,30)||'create'; const db=database(); const now=Date.now();
  if(action==='update_status'){const id=clean(body.id,80);const status=clean(body.status,30);if(!['received','reviewing','clarification','ready_to_quote','quoted','won','lost'].includes(status))return Response.json({error:'Invalid RFQ status.'},{status:400});await requireRfqAccess(context,id);const result=await db.prepare(`UPDATE rfqs SET status=?,updated_at=? WHERE id=? AND workspace_id=?`).bind(status,now,id,context.workspace.id).run();if(!result.meta.changes)return Response.json({error:'RFQ not found.'},{status:404});await auditStatement(context,'rfq.status_updated','rfq',id,{status}).run();return Response.json({ok:true});}
  if(action!=='create')return Response.json({error:'Unknown action.'},{status:400}); const title=clean(body.title,200);const requesterCompany=clean(body.requesterCompany,180);const deadline=clean(body.submissionDeadline,10);if(!title||!requesterCompany)return Response.json({error:'RFQ title and requester company are required.'},{status:400});if(deadline&&!/^\d{4}-\d{2}-\d{2}$/.test(deadline))return Response.json({error:'Deadline must use YYYY-MM-DD.'},{status:400}); const file=form?.get('document');if(file&&(!(file instanceof File)||!allowedFiles.has(file.type)||file.size>15*1024*1024))return Response.json({error:'Use PDF, DOCX, XLSX, CSV, TXT, PNG or JPG files up to 15 MB.'},{status:400});
  if(file instanceof File && await validateUpload(file,allowedFiles,15*1024*1024))return Response.json({error:'The file content must match a PDF, DOCX, XLSX, CSV, TXT, PNG or JPG file up to 15 MB.'},{status:400});
  const id=crypto.randomUUID();const eventId=clean(request.headers.get('x-revenue-event-id'),80);await requireEventAccess(context,eventId);const itemLines=clean(body.items,8000).split(/\r?\n/).map((line)=>line.trim()).filter(Boolean).slice(0,100);const statements=[db.prepare(`INSERT INTO rfqs (id,workspace_id,event_id,title,reference,requester_company,contact_name,delivery_location,submission_deadline,status,processing_status,owner_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,'received',?,?,?,?)`).bind(id,context.workspace.id,eventId,title,clean(body.reference,120)||null,requesterCompany,clean(body.contactName,160)||null,clean(body.deliveryLocation,300)||null,deadline||null,file?'stored_pending_extraction':'manual_review',context.user.id,now,now)];
  for(const line of itemLines){const [product,quantity,...spec]=line.split('|').map((part)=>part.trim());if(product)statements.push(db.prepare(`INSERT INTO rfq_items (id,workspace_id,rfq_id,product,quantity,specifications,source_evidence,created_at) VALUES (?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),context.workspace.id,id,product.slice(0,240),quantity?.slice(0,80)||null,spec.join(' | ').slice(0,3000)||null,line.slice(0,3000),now));}
  let storageKey:string|null=null;if(file instanceof File){const documentId=crypto.randomUUID();const safeName=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-').slice(0,120)||'rfq';storageKey=`${context.workspace.id}/rfqs/${id}/${documentId}-${safeName}`;await revenueEnv().FILES.put(storageKey,file.stream(),{httpMetadata:{contentType:file.type},customMetadata:{workspaceId:context.workspace.id,rfqId:id,uploadedBy:context.user.id}});statements.push(db.prepare(`INSERT INTO rfq_documents (id,workspace_id,rfq_id,original_name,storage_key,content_type,size_bytes,processing_status,created_by,created_at) VALUES (?,?,?,?,?,?,?,'stored_pending_extraction',?,?)`).bind(documentId,context.workspace.id,id,file.name.slice(0,180),storageKey,file.type,file.size,context.user.id,now));}
  statements.push(auditStatement(context,'rfq.created','rfq',id,{hasDocument:Boolean(file),itemCount:itemLines.length}));try{await db.batch(statements);}catch(error){if(storageKey)await revenueEnv().FILES.delete(storageKey);throw error;}return Response.json({rfq:{id,title,requesterCompany,submissionDeadline:deadline,status:'received',processingStatus:file?'stored_pending_extraction':'manual_review',itemCount:itemLines.length,documentCount:file?1:0,createdAt:now}},{status:201});
}
