import { auditStatement,database,eventAccessClause,requireEventAccess,requireLeadAccess,requireRole,requireWorkspace } from '@/lib/db';
import { buildMeetingIcs } from '@/lib/ics';

function clean(value:unknown,max:number){return typeof value==='string'?value.trim().slice(0,max):'';}
function email(value:string){return /^[a-z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$/i.test(value);}

export async function GET(request:Request){
  const context=await requireWorkspace(request);const db=database();const url=new URL(request.url);const id=clean(url.searchParams.get('id'),80);
  if(id&&url.searchParams.get('format')==='ics'){
    const meeting=await db.prepare(`SELECT id,event_id AS eventId,title,starts_at AS startsAt,ends_at AS endsAt,timezone,location,agenda,status FROM meetings WHERE id=? AND workspace_id=?`).bind(id,context.workspace.id).first<{id:string;eventId:string;title:string;startsAt:number;endsAt:number;timezone:string;location:string|null;agenda:string|null;status:string}>();
    if(!meeting)return Response.json({error:'Meeting not found.'},{status:404});await requireEventAccess(context,meeting.eventId);
    const participants=await db.prepare(`SELECT name,email FROM meeting_participants WHERE workspace_id=? AND meeting_id=? ORDER BY created_at`).bind(context.workspace.id,id).all<{name:string|null;email:string}>();
    const filename=`${meeting.title.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').slice(0,60)||'meeting'}.ics`;return new Response(buildMeetingIcs(meeting,participants.results,Date.now()),{headers:{'content-type':'text/calendar; charset=utf-8','content-disposition':`attachment; filename="${filename}"`,'cache-control':'private, no-store'}});
  }
  const selectedEventId=clean(request.headers.get('x-revenue-event-id'),80);if(selectedEventId)await requireEventAccess(context,selectedEventId);const access=eventAccessClause(context,'m.event_id');const eventFilter=selectedEventId?' AND m.event_id=?':'';
  const rows=await db.prepare(`SELECT m.id,m.event_id AS eventId,m.lead_id AS leadId,m.title,m.starts_at AS startsAt,m.ends_at AS endsAt,m.timezone,m.location,m.agenda,m.status,m.cancellation_reason AS cancellationReason,m.version,l.full_name AS leadName,l.company,(SELECT COUNT(*) FROM meeting_participants p WHERE p.workspace_id=m.workspace_id AND p.meeting_id=m.id) AS participantCount FROM meetings m LEFT JOIN leads l ON l.id=m.lead_id AND l.workspace_id=m.workspace_id WHERE m.workspace_id=?${access.sql}${eventFilter} ORDER BY CASE m.status WHEN 'scheduled' THEN 0 ELSE 1 END,m.starts_at ASC LIMIT 100`).bind(context.workspace.id,...access.bindings,...(selectedEventId?[selectedEventId]:[])).all();return Response.json({meetings:rows.results});
}

export async function POST(request:Request){
  const context=await requireWorkspace(request);requireRole(context,['owner','admin','manager','salesperson']);let body:Record<string,unknown>;try{body=await request.json() as Record<string,unknown>;}catch{return Response.json({error:'Invalid request body.'},{status:400});}const action=clean(body.action,30);const db=database();
  if(action==='create'){
    const leadId=clean(body.leadId,80);const title=clean(body.title,200);const location=clean(body.location,300);const agenda=clean(body.agenda,4000);const startsAt=Date.parse(clean(body.startsAt,40));const endsAt=Date.parse(clean(body.endsAt,40));if(!title||!Number.isFinite(startsAt)||!Number.isFinite(endsAt))return Response.json({error:'Title, start and end time are required.'},{status:400});if(endsAt<=startsAt||endsAt-startsAt>24*60*60*1000)return Response.json({error:'Meeting end must be after its start and within 24 hours.'},{status:400});if(startsAt<Date.now()-5*60*1000)return Response.json({error:'Meeting start cannot be in the past.'},{status:400});
    let eventId=clean(request.headers.get('x-revenue-event-id'),80);let lead:{eventId:string;fullName:string;email:string|null}|null=null;if(leadId){const access=await requireLeadAccess(context,leadId);eventId=access.eventId;lead=await db.prepare(`SELECT event_id AS eventId,full_name AS fullName,email FROM leads WHERE id=? AND workspace_id=?`).bind(leadId,context.workspace.id).first<{eventId:string;fullName:string;email:string|null}>()||null;}if(!eventId)return Response.json({error:'Select an event before scheduling a meeting.'},{status:409});await requireEventAccess(context,eventId);const event=await db.prepare(`SELECT timezone FROM events WHERE id=? AND workspace_id=?`).bind(eventId,context.workspace.id).first<{timezone:string}>();if(!event)return Response.json({error:'Event not found.'},{status:404});
    const supplied=clean(body.participantEmails,2000).split(/[;,\n]/).map((item)=>item.trim().toLowerCase()).filter(Boolean);const invalid=supplied.filter((item)=>!email(item));if(invalid.length)return Response.json({error:`Invalid participant email: ${invalid[0]}`},{status:400});const participantMap=new Map<string,{name:string|null;leadId:string|null}>();for(const item of supplied)participantMap.set(item,{name:null,leadId:null});if(lead?.email&&email(lead.email.toLowerCase()))participantMap.set(lead.email.toLowerCase(),{name:lead.fullName,leadId});if(participantMap.size>20)return Response.json({error:'A meeting can have at most 20 external participants.'},{status:400});
    const id=crypto.randomUUID();const now=Date.now();const statements=[db.prepare(`INSERT INTO meetings (id,workspace_id,event_id,lead_id,organizer_id,title,starts_at,ends_at,timezone,location,agenda,status,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,'scheduled',1,?,?)`).bind(id,context.workspace.id,eventId,leadId||null,context.user.id,title,startsAt,endsAt,event.timezone,location||null,agenda||null,now,now),...Array.from(participantMap.entries()).map(([participantEmail,item])=>db.prepare(`INSERT INTO meeting_participants (id,workspace_id,meeting_id,lead_id,name,email,participant_type,response_status,created_at) VALUES (?,?,?,?,?,?,'external','needs_action',?)`).bind(crypto.randomUUID(),context.workspace.id,id,item.leadId,item.name,participantEmail,now)),db.prepare(`INSERT INTO meeting_history (id,workspace_id,meeting_id,action,from_status,to_status,version,actor_id,created_at) VALUES (?,?,?,'created','scheduled','scheduled',1,?,?)`).bind(crypto.randomUUID(),context.workspace.id,id,context.user.id,now),auditStatement(context,'meeting.created','meeting',id,{eventId,participantCount:participantMap.size})];await db.batch(statements);return Response.json({meeting:{id,eventId,leadId:leadId||null,title,startsAt,endsAt,timezone:event.timezone,location:location||null,agenda:agenda||null,status:'scheduled',version:1,leadName:lead?.fullName||null,participantCount:participantMap.size}},{status:201});
  }
  if(action==='transition'){
    const id=clean(body.id,80);const command=clean(body.command,20);const version=Number(body.version);const reason=clean(body.reason,1000);if(!id||!Number.isInteger(version)||version<1)return Response.json({error:'Meeting id and current version are required.'},{status:400});const meeting=await db.prepare(`SELECT event_id AS eventId,status,version FROM meetings WHERE id=? AND workspace_id=?`).bind(id,context.workspace.id).first<{eventId:string;status:string;version:number}>();if(!meeting)return Response.json({error:'Meeting not found.'},{status:404});await requireEventAccess(context,meeting.eventId);if(meeting.version!==version)return Response.json({error:'This meeting changed in another session. Reload before updating it.',code:'VERSION_CONFLICT'},{status:409});let nextStatus='';if(command==='complete'&&meeting.status==='scheduled')nextStatus='complete';else if(command==='cancel'&&meeting.status==='scheduled'){if(!reason)return Response.json({error:'A cancellation reason is required.'},{status:400});nextStatus='cancelled';}else if(command==='reopen'&&['complete','cancelled'].includes(meeting.status)){if(!reason)return Response.json({error:'A reopen reason is required.'},{status:400});nextStatus='scheduled';}else return Response.json({error:'This meeting cannot make that transition.'},{status:409});const now=Date.now();const mutationToken=crypto.randomUUID();const nextVersion=version+1;const detail=JSON.stringify({fromStatus:meeting.status,toStatus:nextStatus,version:nextVersion});const results=await db.batch([db.prepare(`UPDATE meetings SET status=?,cancellation_reason=?,version=version+1,mutation_token=?,updated_at=? WHERE id=? AND workspace_id=? AND status=? AND version=?`).bind(nextStatus,nextStatus==='cancelled'?reason:null,mutationToken,now,id,context.workspace.id,meeting.status,version),db.prepare(`INSERT INTO meeting_history (id,workspace_id,meeting_id,action,from_status,to_status,reason,version,actor_id,created_at) SELECT ?,m.workspace_id,m.id,?,?,?,?,?,?,? FROM meetings m WHERE m.id=? AND m.workspace_id=? AND m.mutation_token=? AND m.version=?`).bind(crypto.randomUUID(),command,meeting.status,nextStatus,reason||null,nextVersion,context.user.id,now,id,context.workspace.id,mutationToken,nextVersion),db.prepare(`INSERT INTO audit_events (id,workspace_id,actor_id,action,entity_type,entity_id,detail_json,created_at) SELECT ?,m.workspace_id,?,?,'meeting',m.id,?,? FROM meetings m WHERE m.id=? AND m.workspace_id=? AND m.mutation_token=? AND m.version=?`).bind(crypto.randomUUID(),context.user.id,`meeting.${command}`,detail,now,id,context.workspace.id,mutationToken,nextVersion)]);if(!results[0].meta.changes)return Response.json({error:'This meeting changed in another session. Reload before updating it.',code:'VERSION_CONFLICT'},{status:409});return Response.json({meeting:{id,status:nextStatus,cancellationReason:nextStatus==='cancelled'?reason:null,version:nextVersion}});
  }
  return Response.json({error:'Unknown action.'},{status:400});
}
